### PR TITLE
Added UTF-8 support

### PR DESCRIPTION
**Pull request by anemo-hypostasis**
Tested using Device.ExecuteShellCommand, but it doesn't crash so it should be good with everything else.

Not thoroughly tested yet, but it should be good.

### CODE REVIEW

**Comment by camalot** [comment]
Instead of calling `Encoding.UTF8` can you have it use the encoding variable, so if that is configurable in the future, it doesn't require changes to the calls, it will just require the work to make the encoding configurable. 

Can you give an example, of when the old encoding was not working?

**Comment by anemo-hypostasis** [comment]
I've tested it on [ADBKeyboard](https://github.com/senzhk/ADBKeyBoard), and I also tried to create my own BroadcaseReceiver on Android just to be on the safe side. Narrowed it down to this library's `FormAdbRequest ( String req )` method.

Tested using this command with Vietnamese text:
`adb shell am broadcast -a ADB_INPUT_TEXT --es msg 'con cáo nâu nhanh chóng
'`

Expected text: con cáo nâu nhanh chóng
Actual text: con cᯠnⵠnhanh ch㮧
Actual text with this commit: con cáo nâu nhanh chóng

**Comment by anemo-hypostasis** [comment]
I'll push some changes probably tomorrow.

**Comment by camalot** [comment]
Perfect, Thanks. I knew there were situations like that, but wanted a real example to be documented.

**Pull request closed without merging**
